name: single_app
description: "A Flutter demo for single app projects"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^13.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true